spring:
  rabbitmq:
    host: 
    port: 
    username: 
    password: 
    virtual-host: /
    listener:
      type: direct
      direct:
#        设置手动签收
        acknowledge-mode: manual
        default-requeue-rejected: false
        prefetch: 10
